import {User} from "../user";

export const users:User[]=[
  {
    id:0,
    userName:"geekgod",
    avatar:"#",
    friends:[
      {
        friendName:"chandler",
        userId:1,
        chatId:0,
      },
      {
        friendName:"stillsingle",
        userId:2,
        chatId:1,
      }
    ],
  },
  {
    id:1,
    userName:"chandler",
    avatar:"#",
    friends:[
      {
        friendName:"geekgod",
        userId:0,
        chatId:0,
      },
      {
        friendName:"kamdev",
        userId:3,
        chatId:2,
      }
    ],
  },
  {
    id:2,
    userName:"stillsingle",
    avatar:"#",
    friends:[
      {
        friendName:"geekgod",
        userId:0,
        chatId:1,
      }
    ],
  },
  {
    id:3,
    userName:"kamdev",
    avatar:"#",
    friends:[
      {
        friendName:"chandler",
        userId:1,
        chatId:2,
      }
    ],
  },
]
