import {User} from "../user";

export const users:User[]=[
  {
    id:0,
    userName:"geekgod",
    avatar:"#",
    friends:[
      {
        friendName:"chandler",
        userId:1,
        chatId:0,
      },
      {
        friendName:"stillsingle",
        userId:2,
        chatId:1,
      }
    ],
    blocked:[
      {
        friendName:"abc",
        userId:11,
        chatId:0,
      },
      {
        friendName:"def",
        userId:12,
        chatId:0,
      }
    ]
  },
  {
    id:1,
    userName:"chandler",
    avatar:"#",
    friends:[
      {
        friendName:"geekgod",
        userId:0,
        chatId:0,
      },
      {
        friendName:"kamdev",
        userId:3,
        chatId:2,
      }
    ],
    blocked:[],
  },
  {
    id:2,
    userName:"stillsingle",
    avatar:"#",
    friends:[
      {
        friendName:"geekgod",
        userId:0,
        chatId:1,
      }
    ],
    blocked:[],
  },
  {
    id:3,
    userName:"kamdev",
    avatar:"#",
    friends:[
      {
        friendName:"chandler",
        userId:1,
        chatId:2,
      }
    ],
    blocked:[],
  },{
    id:11,
    userName:"abc",
    avatar:"#",
    friends:[],
    blocked:[]
  },{
    id:12,
    userName:"def",
    avatar:"#",
    friends:[],
    blocked:[]
  },
]
